### ISSUE TITLE
When guava 14 is available, cleanup RestAnnotationProcessor

### ISSUE THREAD

**Issue by adriancole** [jclouds/legacy-jclouds#1023]
There's considerable code related to what we need in RestAnnotationProcessor in guava 14, including the following:

http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/reflect/Parameter.html
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/reflect/Invokable.html

**Comment by andrewgaul** [comment]
Done in afc070ac07542b82c90ec6a77b9d136e58da4446 and subsequent commits.
