### ISSUE TITLE
jclouds does not support Terremark Ecloud Latest API 

### ISSUE THREAD

**Issue by suniluiit** [jclouds/legacy-jclouds#1031]
Hi ,
Currently Jcloud only support TM  ecloud api 2.8. The Enterprise Cloud Application Programming Interface (API) release 2.8 revision 1, the final version of the previous API design and released on 29 July 2011, is retired and no longer supported.  ecloud api 2.8.  will be supported by TM till Dec 2012.

Jcloud is not supporting latest version of TM . Can you please help us when jacloud will support latest TM API.

Current Version Of Jcloud I am using:
1.5.3

**Comment by andrewgaul** [comment]
Terremark provider removed in ddfefd7ec7cc49c1796ab6131d3e6e8fbd75aa7d.
