### ISSUE TITLE
support implicit aws credentials via IAM roles

### ISSUE THREAD

**Issue by jclouds** [jclouds/legacy-jclouds#1280]
Currently, it is possible to use temporary keys generated via IAM (using `aws-sts`) or IAM roles by making your own `Supplier<Credentials>` and passing that to `ContextBuilder.credentialsSupplier`.  Some have asked for a parameterless option that uses the instance metadata service when in EC2.  

This would look like `ContextBuilder.newBuilder("aws-s3").buildView(BlobStoreContext.class)` notably lacking the credentials part.

This isn't hard to do.  All we need to do is create an implicit credentials supplier, and look up the metadata service to obtain credentials, falling back to properties or whatnot.

In doing this, folks wouldn't need to craft their own credentials supplier for the common case of auto-detecting credentials when running in ec2.

http://aws.typepad.com/aws/2012/06/iam-roles-for-ec2-instances-simplified-secure-access-to-aws-service-apis-from-ec2.html

**Comment by chadmaughan** [comment]
This would be a fantastic feature.  Is there an example of providing `Supplier<Credentials>` from an IAM role for AWS as part of a workaround?  I've searched around without much luck.

Thanks!

**Comment by demobox** [comment]
@chadmaughan The legacy-jclouds repos aren't in use any more. Please have a look at jclouds/jclouds and ping [user@apache.jclouds.org](http://jclouds.apache.org/community/) for questions.

Thanks!

**Comment by deyanTG** [comment]
Hi, is this feature possible now? I've searched through the docs but I haven't found a solution

**Comment by cobyrne09** [comment]
+1
