### ISSUE TITLE
Rackspace US regions are not supported

### ISSUE THREAD

**Issue by timuralp** [jclouds/legacy-jclouds#1283]
Reopening the code.google.com issue 1101.

1. Create a blobstore object for Rackspace US
2. Run something like this:
   for (Location loc: Blobstore.listAssignableLocations()){
     System.out.println(loc.getId());
   }
3. Check the output at the command prompt

What is the expected output? What do you see instead?
Chicago
Dallas

The output I see right now is:
DEFAULT -- the other regions do not seem to be recognized parameters for cloudfiles-us

What version of the product are you using? On what operating system?
jclouds 1.5.1 on Linux

**Comment by andrewgaul** [comment]
Supported via opestack-swift provider in jclouds 1.9.1.
