### ISSUE TITLE
HP Cloud US East BlobStore location is not supported

### ISSUE THREAD

**Issue by ntolia** [jclouds/legacy-jclouds#1284]
When I run the following code for HP Cloud's Object store with jclouds 1.5.5, I would expect us to see two regions: region-a.geo-1 and region-b.geo-1

```
        for (Location loc : blobStore.listAssignableLocations()) {
            System.out.println(loc.getId());
        }
```

but I only see region-a.geo-1 (US West) and not region-b.geo-1 (US East). Would be great to fix this so that our users can select between both regions.

**Comment by gaul** [comment]
HP Cloud is defunct.
