### ISSUE TITLE
Signed Jars

### ISSUE THREAD

**Issue by tiagoMO** [jclouds/legacy-jclouds#1294]
hi all :)

I have an issue and maybe someone can help me.

I am using jclouds to access rackspace cloud files uk and windows azure to store my aplication data. I would like to build a jar containing all jars that i need, i mean, all 3ª party jars (guice, guava, etc....) and cloud files and azure jars (azure blob, azure common, etc..). I already have do this with previous jclouds versions, but since the 1.5.4 version contains signed jars, i can't do it. :/ 

Need some help please.

Thanks

**Comment by andrewgaul** [comment]
Should not be a problem in 1.9.0 release.
