### ISSUE TITLE
Using an existing key pair and runScriptOnNodesMatching

### ISSUE THREAD

**Issue by PoornimaBS** [jclouds/legacy-jclouds#1582]
Hi,

I have started using jclouds from past few days. I have some doubts.

After some googling i came to know how we use an existing key pair as below,
```
Template template = templateBuilder.build();
            template.getOptions().as(AWSEC2TemplateOptions.class).subnetId("subnet-a1e1d08b").
            keyPair("jclouds#jcloud").overrideLoginPrivateKey(login.credential);
```
The above code uses the existing keypair.

But when i try to run script on nodes, it fails giving error Authetication Exception,
```
Map<? extends NodeMetadata, ExecResponse> responses = compute.runScriptOnNodesMatching(//
                  inGroup(groupName), // predicate used to select nodes
                  exec(command), // what you actually intend to run
                  overrideLoginCredentials(login) // use my local user &
                                                 // ssh key
                        .runAsRoot(false) // don't attempt to run as root (sudo)
                        .wrapInInitScript(false));// run command directly
```
Please let me know if i have to make any changes

**Comment by nacx** [comment]
Hi @PoornimaBS. This repo is obsolete and is here just as an archive of previous issues and releases.

The current jclouds repo is: https://github.com/jclouds/jclouds
And the issue tracker is at: https://issues.apache.org/jira/browse/JCLOUDS

Please, [report issues there](https://jclouds.apache.org/reference/report-a-bug/) and ask for feedback in [our mailing lists](https://jclouds.apache.org/community/).
