### ISSUE TITLE
jclouds-virtualbox test fails on Debian - md5sum exists but md5 does not

### ISSUE THREAD

**Issue by ieugen** [jclouds/legacy-jclouds#932]
MastersLoadingCache class tests the for an image hash, but md5 command is not available on Debian.   

I'm using Debian Wheezy (unreleased) but that should not matter.

The command to compute hash functions is md5sum and also does not contain "=" . Besides that, why not use a Java md5 implementation to be cross platform? 

      ExecResponse response = runScriptOnNodeFactory
            .create(
                  hostNodeMetadata,
                  Statements.exec("md5 " + isosDir + File.separator + fileName),
                  runAsRoot(false)).init().call();
      if (md5 != null) {
         if (!Iterables.get(
               Splitter.on("=").trimResults().split(response.getOutput()), 1)
               .equals(md5))
            return null;
      }

**Comment by andrewgaul** [comment]
Virtualbox provider removed in jclouds/jclouds-labs@75178c7708260d9d9e3a70161b88a9dd6985a726.
